version: "3.7"

services:
    app:
        build:
            args:
                user: aldar
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: maxmoll
        container_name: maxmoll-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - maxmoll

    db:
        image: mysql:latest
        container_name: maxmoll-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - maxmoll
        ports:
            - 3307:3306

    nginx:
        image: nginx:1.25-alpine
        container_name: maxmoll-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - maxmoll

networks:
    maxmoll:
        driver: bridge
